import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/providers.dart';
import '../../../core/models/models.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/common.dart';

class DashboardScreen extends ConsumerStatefulWidget {
  const DashboardScreen({super.key});
  @override ConsumerState<DashboardScreen> createState() => _DashboardState();
}
class _DashboardState extends ConsumerState<DashboardScreen> {
  Timer? timer;
  @override void initState() { super.initState(); timer = Timer.periodic(const Duration(seconds: 15), (_) { ref.invalidate(serverProvider); ref.invalidate(botsProvider); }); }
  @override void dispose() { timer?.cancel(); super.dispose(); }
  @override Widget build(BuildContext context) {
    final server = ref.watch(serverProvider); final user = ref.watch(authProvider); final bots = ref.watch(botsProvider);
    return RefreshIndicator(onRefresh: () async { ref.invalidate(serverProvider); ref.invalidate(botsProvider); ref.invalidate(announcementsProvider); }, child: server.when(loading: () => const LoadingView(), error: (e, _) => ErrorView(message: e.toString(), retry: () => ref.invalidate(serverProvider)), data: (value) => ListView(padding: const EdgeInsets.all(AppTheme.pagePadding), children: [
      Text('Welcome back', style: Theme.of(context).textTheme.titleMedium?.copyWith(color: AppTheme.muted)), Text(user.username.isEmpty ? 'Developer' : user.username, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), Text(user.role == 'admin' ? 'Control Center' : 'Cloud Control Panel', style: const TextStyle(color: AppTheme.primary)), const SizedBox(height: 22), ServerSummary(server: value), const SizedBox(height: 14),
      bots.when(loading: () => const LinearProgressIndicator(), error: (_, __) => const SizedBox.shrink(), data: (items) { final running = items.where((b) => b.state.toLowerCase() == 'running').length; return Card(child: ListTile(leading: const Icon(Icons.smart_toy_outlined, color: AppTheme.primary), title: const Text('Bot Summary'), subtitle: Text('$running running • ${items.length} total'), trailing: const Icon(Icons.chevron_right), onTap: () => context.go('/bots'))); }), const SizedBox(height: 22), const SectionTitle('Quick Actions'), Wrap(spacing: 10, runSpacing: 10, children: [ActionButton(label: 'Console', icon: Icons.terminal, onTap: () => context.go('/server')), ActionButton(label: 'Files', icon: Icons.folder_outlined, onTap: () => context.go('/files')), ActionButton(label: 'Bots', icon: Icons.smart_toy_outlined, onTap: () => context.go('/bots')), ActionButton(label: 'Backups', icon: Icons.backup_outlined, onTap: () => context.go('/backups'))]), const SizedBox(height: 22), const SectionTitle('Resources'), ResourceBar(label: 'CPU', value: (value.resources.cpu / 100).clamp(0, 1), caption: '${value.resources.cpu.toStringAsFixed(1)}%'), const SizedBox(height: 12), ResourceBar(label: 'Memory', value: value.resources.memoryTotal == 0 ? 0 : (value.resources.memoryBytes / value.resources.memoryTotal).clamp(0, 1), caption: bytesText(value.resources.memoryBytes)), const SizedBox(height: 12), ResourceBar(label: 'Disk', value: value.resources.diskTotal == 0 ? 0 : (value.resources.diskBytes / value.resources.diskTotal).clamp(0, 1), caption: bytesText(value.resources.diskBytes)), const SizedBox(height: 22), const SectionTitle('Recent Activity'), Card(child: ListTile(leading: Icon(value.running ? Icons.check_circle : Icons.info_outline, color: value.running ? AppTheme.success : AppTheme.warning), title: Text(value.running ? 'Server is running' : 'Server is ${value.state}'), subtitle: Text('Uptime ${uptimeText(value.resources.uptime)}'))), const SizedBox(height: 22), const SectionTitle('Announcements'), ref.watch(announcementsProvider).when(loading: () => const LinearProgressIndicator(), error: (_, __) => const Text('Unable to load announcements', style: TextStyle(color: AppTheme.muted)), data: (items) => items.isEmpty ? const EmptyView(title: 'No announcements', subtitle: 'You are up to date') : Column(children: items.take(3).map((a) => Card(child: ListTile(leading: const Icon(Icons.campaign_outlined, color: AppTheme.secondary), title: Text(a.text)))).toList())),
    ])));
  }
}
class ResourceBar extends StatelessWidget { const ResourceBar({required this.label, required this.value, required this.caption, super.key}); final String label, caption; final double value; @override Widget build(BuildContext c) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(label, style: const TextStyle(fontWeight: FontWeight.w600)), Text(caption, style: const TextStyle(color: AppTheme.muted))]), const SizedBox(height: 7), ClipRRect(borderRadius: BorderRadius.circular(8), child: LinearProgressIndicator(value: value, minHeight: 8, backgroundColor: Colors.white10, color: AppTheme.primary))]); }
class ServerSummary extends StatelessWidget { const ServerSummary({required this.server, super.key}); final ServerModel server; @override Widget build(BuildContext c) => Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(width: 10, height: 10, decoration: BoxDecoration(color: server.running ? AppTheme.success : AppTheme.danger, shape: BoxShape.circle)), const SizedBox(width: 10), Expanded(child: Text(server.name.isEmpty ? 'Server' : server.name, style: Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold))), Text(server.running ? 'ONLINE' : server.state.toUpperCase(), style: TextStyle(color: server.running ? AppTheme.success : AppTheme.warning, fontWeight: FontWeight.bold))]), const SizedBox(height: 20), Row(children: [_stat('CPU', '${server.resources.cpu.toStringAsFixed(1)}%'), _stat('RAM', bytesText(server.resources.memoryBytes)), _stat('DISK', bytesText(server.resources.diskBytes))]), const SizedBox(height: 14), Text('RX ${bytesText(server.resources.networkRx)}  •  TX ${bytesText(server.resources.networkTx)}', style: const TextStyle(color: AppTheme.muted, fontSize: 12))]))); Widget _stat(String a, String b) => Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(a, style: const TextStyle(color: AppTheme.muted, fontSize: 12)), const SizedBox(height: 5), Text(b, style: const TextStyle(fontWeight: FontWeight.w700))])); }
class ActionButton extends StatelessWidget { const ActionButton({required this.label, required this.icon, required this.onTap, super.key}); final String label; final IconData icon; final VoidCallback onTap; @override Widget build(BuildContext c) => OutlinedButton.icon(onPressed: onTap, icon: Icon(icon), label: Text(label), style: OutlinedButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14), foregroundColor: AppTheme.primary, side: const BorderSide(color: AppTheme.border))); }

class ServerScreen extends ConsumerStatefulWidget { const ServerScreen({super.key}); @override ConsumerState<ServerScreen> createState() => _ServerState(); }
class _ServerState extends ConsumerState<ServerScreen> {
  bool busy = false; final commandController = TextEditingController(); final output = <String>[];
  @override void dispose() { commandController.dispose(); super.dispose(); }
  Future<void> power(String signal) async { if (!await confirmServer(context, '$signal server?', 'This operation affects the live server.')) return; setState(() => busy = true); try { await ref.read(repositoryProvider).power(signal); ref.invalidate(serverProvider); if (mounted) feedback(context, '$signal completed', true); } catch (e) { if (mounted) feedback(context, e.toString(), false); } finally { if (mounted) setState(() => busy = false); } }
  Future<void> sendCommand() async { final command = commandController.text.trim(); if (command.isEmpty) return; setState(() => busy = true); try { final result = await ref.read(repositoryProvider).commandOutput(command); setState(() { output.add('> $command'); output.add(result); }); commandController.clear(); } catch (e) { setState(() => output.add(e.toString())); } finally { if (mounted) setState(() => busy = false); } }
  Widget consoleCard() {
    return Card(child: Padding(padding: const EdgeInsets.all(14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      const Text('Server Console', style: TextStyle(fontWeight: FontWeight.w700)),
      const SizedBox(height: 10),
      Container(height: 180, width: double.infinity, padding: const EdgeInsets.all(12), color: const Color(0xFF030504), child: SingleChildScrollView(child: SelectableText(output.isEmpty ? 'Command output will appear here.' : output.join('\n'), style: const TextStyle(fontFamily: 'monospace', color: AppTheme.primary)))),
      const SizedBox(height: 10),
      Row(children: [Expanded(child: TextField(controller: commandController, maxLength: 500, onSubmitted: (_) => sendCommand(), decoration: const InputDecoration(hintText: 'Enter command...'))), IconButton(onPressed: busy ? null : sendCommand, icon: const Icon(Icons.send))]),
      Row(children: [TextButton.icon(onPressed: () => setState(output.clear), icon: const Icon(Icons.clear_all), label: const Text('Clear')), TextButton.icon(onPressed: () => Clipboard.setData(ClipboardData(text: output.join('\n'))), icon: const Icon(Icons.copy), label: const Text('Copy'))]),
    ])));
  }
  @override Widget build(BuildContext c) { return ListView(padding: const EdgeInsets.all(AppTheme.pagePadding), children: [ref.watch(serverProvider).when(loading: () => const LoadingView(), error: (e, _) => ErrorView(message: e.toString(), retry: () => ref.invalidate(serverProvider)), data: (server) => ServerSummary(server: server)), const SizedBox(height: 20), const SectionTitle('Power controls'), Wrap(spacing: 10, runSpacing: 10, children: [FilledButton.icon(onPressed: busy ? null : () => power('start'), icon: const Icon(Icons.play_arrow), label: const Text('START')), OutlinedButton.icon(onPressed: busy ? null : () => power('restart'), icon: const Icon(Icons.restart_alt), label: const Text('RESTART')), OutlinedButton.icon(onPressed: busy ? null : () => power('stop'), icon: const Icon(Icons.stop), label: const Text('STOP')), OutlinedButton.icon(onPressed: busy ? null : () => power('shutdown'), icon: const Icon(Icons.power_settings_new), label: const Text('SHUTDOWN'))]), const SizedBox(height: 22), consoleCard(), const SizedBox(height: 20), const SectionTitle('Processes'), const SizedBox(height: 260, child: ProcessesPreview())]); }
}
class ProcessesPreview extends ConsumerWidget { const ProcessesPreview({super.key}); @override Widget build(BuildContext c, WidgetRef r) => r.watch(processesProvider).when(loading: () => const LoadingView(), error: (e, _) => ErrorView(message: e.toString(), retry: () => r.invalidate(processesProvider)), data: (items) => items.isEmpty ? const EmptyView(title: 'No processes', subtitle: 'The backend returned no process data') : ListView.builder(itemCount: items.length, itemBuilder: (_, i) { final p = items[i]; return ListTile(dense: true, leading: Text('${p.pid}', style: const TextStyle(color: AppTheme.muted)), title: Text(p.name), subtitle: Text('${p.status} • CPU ${p.cpu}% • RAM ${bytesText(p.ram)}')); })); }
Future<bool> confirmServer(BuildContext c, String title, String message) async => await showDialog<bool>(context: c, builder: (_) => AlertDialog(title: Text(title), content: Text(message), actions: [TextButton(onPressed: () => Navigator.pop(c, false), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(c, true), child: const Text('Continue'))])) ?? false;
void feedback(BuildContext c, String text, bool success) { ScaffoldMessenger.of(c).showSnackBar(SnackBar(content: Text(text), backgroundColor: success ? AppTheme.surfaceElevated : AppTheme.danger)); }
