import 'package:dio/dio.dart';
import 'dart:typed_data';
import '../models/models.dart';
import 'api_client.dart';

List<T> _models<T>(dynamic data, T Function(Map<String,dynamic>) parse) {
  final list = data is Map ? (data['items'] ?? data['users'] ?? data['bots'] ?? data['files'] ?? data['backups'] ?? data['notifications'] ?? data['requests'] ?? data['logs'] ?? const []) : data;
  return (list is List ? list : const []).whereType<Map>().map((x) => parse(Map<String,dynamic>.from(x))).toList();
}
Map<String,dynamic> _json(dynamic data) => data is Map ? Map<String,dynamic>.from(data) : <String,dynamic>{};
String _text(dynamic data) => data is Map ? (data['logs'] ?? data['content'] ?? data['text'] ?? data['output'] ?? '').toString() : data?.toString() ?? '';

class HostingRepository {
  HostingRepository(this.api); final ApiClient api;
  Future<bool> health()=>api.get('/health').then((_)=>true);
  Future<SessionModel> login(String u,String p)=>api.post('/auth/login',data:{'username':u,'password':p}).then((j)=>SessionModel.fromJson(_json(j)));
  Future<SessionModel> register(String u,String p,String invite)=>api.post('/auth/register',data:{'username':u,'password':p,'invite':invite}).then((j)=>SessionModel.fromJson(_json(j)));
  Future<UserProfile> me()=>api.get('/me').then((j)=>UserProfile.fromJson(_json(j)));
  Future<void> changePassword(String oldPassword,String newPassword)=>api.post('/me/password',data:{'old_password':oldPassword,'new_password':newPassword});
  Future<void> logoutAll()=>api.post('/auth/logout-all');
  Future<List<AnnouncementModel>> announcements()=>api.get('/announcements').then((j)=>_models(j,AnnouncementModel.fromJson));
  Future<List<NotificationModel>> notifications({bool unread=false,int limit=50})=>api.get('/notifications',q:{'unread':unread,'limit':limit.clamp(1,200)}).then((j)=>_models(j,NotificationModel.fromJson));
  Future<void> readNotifications(List<int> ids)=>api.post('/notifications/read',data:{'ids':ids});
  Future<void> clearNotifications()=>api.delete('/notifications');
  Future<ServerResources> serverResources()=>api.get('/server/resources').then((j)=>ServerResources.fromJson(_json(j)));
  Future<List<ProcessModel>> processes()=>api.get('/server/processes').then((j)=>_models(j,ProcessModel.fromJson));
  Future<ServerModel> server()=>api.get('/server').then((j)=>ServerModel.fromJson(_json(j)));
  Future<void> power(String signal)=>api.post('/server/power',data:{'signal':signal});
  Future<void> setAutoRestart(bool enabled)=>api.put('/server/auto-restart',data:{'enabled':enabled});
  Future<String> commandOutput(String command)=>api.post('/server/command',data:{'command':command}).then(_text);
  Future<void> command(String command)=>commandOutput(command).then((_){});
  Future<void> reinstall()=>api.post('/server/reinstall',data:{'confirm':'REINSTALL'});
  Future<List<StartupVariable>> startup()=>api.get('/startup').then((j)=>_models(j,StartupVariable.fromJson));
  Future<void> setStartup(String key,String value)=>api.put('/startup/variable',data:{'key':key,'value':value});
  Future<List<FileModel>> files(String dir)=>api.get('/files',q:{'directory':dir}).then((j)=>_models(j,FileModel.fromJson));
  Future<FileMeta> fileMeta(String path)=>api.get('/files/meta',q:{'path':path}).then((j)=>FileMeta.fromJson(_json(j)));
  Future<List<SearchFileModel>> searchFiles(String q,{String directory='/',int maxDepth=4,int limit=100})=>api.get('/files/search',q:{'q':q,'directory':directory,'max_depth':maxDepth.clamp(1,8),'limit':limit.clamp(1,500)}).then((j)=>_models(j,SearchFileModel.fromJson));
  Future<String> readFile(String path)=>api.get('/files/content',q:{'file':path}).then(_text);
  Future<void> writeFile(String path,String content)=>api.post('/files/write',data:{'file':path,'content':content});
  Future<void> uploadFile(Uint8List bytes,String name,String dir,{ProgressCallback? onProgress})=>api.upload('/files/upload',bytes,name,query:{'directory':dir},field:'f',onProgress:onProgress);
  Future<String> downloadUrl(String path)=>api.get('/files/download',q:{'file':path}).then((j)=>_json(j)['url'].toString());
  Future<void> mkdir(String root,String name)=>api.post('/files/mkdir',data:{'root':root,'name':name});
  Future<void> rename(String root,String old,String n)=>batch('rename',[old],root:root,newNames:[n]);
  Future<void> copy(String location)=>batch('copy',[location]);
  Future<void> deleteFiles(String root,List<String> files)=>batch('delete',files,root:root);
  Future<void> batch(String op,List<String> items,{String? root,String? destination,List<String>? newNames,String? mode})=>api.post('/files/batch',data:{'op':op,'items':items,'root':root,'destination':destination,'new_names':newNames,'mode':mode});
  Future<List<UploadModel>> uploads()=>api.get('/uploads').then((j)=>_models(j,UploadModel.fromJson));
  Future<UploadModel> initUpload(String filename,int size,{String directory='/',int? chunkSize})=>api.post('/uploads',data:{'filename':filename,'size':size,'directory':directory,'chunk_size':chunkSize}).then((j)=>UploadModel.fromJson(_json(j)));
  Future<dynamic> uploadChunk(String id,int index,Uint8List bytes)=>api.put('/uploads/$id/chunks/$index',data:bytes);
  Future<UploadModel> uploadStatus(String id)=>api.get('/uploads/$id').then((j)=>UploadModel.fromJson(_json(j)));
  Future<void> cancelUpload(String id)=>api.delete('/uploads/$id');
  Future<void> completeUpload(String id)=>api.post('/uploads/$id/complete');
  Future<List<BackupModel>> backups()=>api.get('/backups').then((j)=>_models(j,BackupModel.fromJson));
  Future<BackupModel> backup(String id)=>api.get('/backups/$id').then((j)=>BackupModel.fromJson(_json(j)));
  Future<void> createBackup(String name,{bool locked=false})=>api.post('/backups',data:{'name':name,'locked':locked});
  Future<void> restoreBackup(String id,bool truncate)=>api.post('/backups/$id/restore',data:{'truncate':truncate});
  Future<void> lockBackup(String id)=>api.post('/backups/$id/lock');
  Future<String> backupUrl(String id)=>api.get('/backups/$id/download').then((j)=>_json(j)['url'].toString());
  Future<void> deleteBackup(String id)=>api.delete('/backups/$id');
  Future<BackupPolicy> backupPolicy()=>api.get('/backups/policy').then((j)=>BackupPolicy.fromJson(_json(j)));
  Future<void> setBackupPolicy(BackupPolicy policy)=>api.put('/backups/policy',data:{'enabled':policy.enabled,'interval_hours':policy.intervalHours,'keep':policy.keep});
  Future<Map<String,dynamic>> restoreStatus()=>api.get('/backups/restore-status').then(_json);
  Future<void> deployBots()=>api.post('/bots/deploy');
  Future<List<BotModel>> bots()=>api.get('/bots').then((j)=>_models(j,BotModel.fromJson));
  Future<void> uploadBot(Uint8List bytes,String name,{String env='{}',Uint8List? requirementsBytes})=>api.upload('/bots',bytes,name,query:{'name':name,'env':env},field:'file',requirementsBytes:requirementsBytes);
  Future<void> startBot(String f)=>api.post('/bots/${Uri.encodeComponent(f)}/start');
  Future<void> stopBot(String f)=>api.post('/bots/${Uri.encodeComponent(f)}/stop');
  Future<void> restartBot(String f)=>api.post('/bots/${Uri.encodeComponent(f)}/restart');
  Future<void> toggleBot(String f,bool enabled)=>enabled?startBot(f):stopBot(f);
  Future<void> setBotPolicy(String f,BotPolicy p)=>api.put('/bots/${Uri.encodeComponent(f)}/policy',data:{'mode':p.mode,'delay':p.delay,'max_fast_crashes':p.maxFastCrashes});
  Future<void> setBotEnv(String f,String k,String v)=>api.put('/bots/${Uri.encodeComponent(f)}/env',data:{'key':k,'value':v});
  Future<void> deleteBotEnv(String f,String k)=>api.delete('/bots/${Uri.encodeComponent(f)}/env/${Uri.encodeComponent(k)}');
  Future<void> removeBot(String f,bool deleteFile)=>api.delete('/bots/${Uri.encodeComponent(f)}',q:{'delete_file':deleteFile});
  Future<Map<String,dynamic>> botStatus(String f)=>api.get('/bots/${Uri.encodeComponent(f)}/status').then(_json);
  Future<List<CrashModel>> botCrashes(String f)=>api.get('/bots/${Uri.encodeComponent(f)}/crashes').then((j)=>_models(j,CrashModel.fromJson));
  Future<String> botLogs(String f,{int lines=200})=>api.get('/bots/${Uri.encodeComponent(f)}/logs',q:{'lines':lines.clamp(1,2000)}).then(_text);
  Future<void> clearBotLogs(String f)=>api.delete('/bots/${Uri.encodeComponent(f)}/logs');
  Future<List<AdminRequest>> adminRequests({String status='pending'})=>api.get('/admin/requests',q:{'status':status}).then((j)=>_models(j,AdminRequest.fromJson));
  Future<void> approveRequest(int id,{int? days,int? maxBots})=>api.post('/admin/requests/$id/approve',data:{'days':days,'max_bots':maxBots});
  Future<void> rejectRequest(int id,String reason)=>api.post('/admin/requests/$id/reject',data:{'reason':reason});
  Future<void> bulk(List<int> ids,String action,{String? reason,int? days,String? text})=>api.post('/admin/bulk',data:{'user_ids':ids,'action':action,'reason':reason,'days':days,'text':text});
  Future<void> createUser(String username,String password,{int? days})=>api.post('/admin/users',data:{'username':username,'password':password,'days':days});
  Future<AdminStats> adminStats()=>api.get('/admin/stats').then((j)=>AdminStats.fromJson(_json(j)));
  Future<List<AdminUserModel>> adminUsers({String search='',bool? banned})=>api.get('/admin/users',q:{'search':search,'banned':banned}).then((j)=>_models(j,AdminUserModel.fromJson));
  Future<AdminUserModel> adminUser(int id)=>api.get('/admin/users/$id').then((j)=>AdminUserModel.fromJson(_json(j)));
  Future<void> deleteUser(int id,{required bool wipe})=>api.delete('/admin/users/$id',q:{'wipe':wipe});
  Future<void> banUser(int id,String reason,bool killServer)=>api.post('/admin/users/$id/ban',data:{'reason':reason,'kill_server':killServer});
  Future<void> unbanUser(int id)=>api.post('/admin/users/$id/unban');
  Future<void> adminPassword(int id,String password)=>api.post('/admin/users/$id/password',data:{'new_password':password});
  Future<void> setUserRole(int id,String role)=>api.post('/admin/users/$id/role',data:{'role':role});
  Future<void> setUserExpiry(int id,int? days,bool extend)=>api.post('/admin/users/$id/expiry',data:{'days':days,'extend':extend});
  Future<void> setMaxBots(int id,int? maxBots)=>api.post('/admin/users/$id/max-bots',data:{'max_bots':maxBots});
  Future<void> setUserNote(int id,String note)=>api.post('/admin/users/$id/note',data:{'note':note});
  Future<void> messageUser(int id,String text)=>api.post('/admin/users/$id/message',data:{'text':text});
  Future<void> forceLogout(int id)=>api.post('/admin/users/$id/logout');
  Future<void> adminPower(int id,String signal)=>api.post('/admin/users/$id/power',data:{'signal':signal});
  Future<void> wipeUser(int id)=>api.post('/admin/users/$id/wipe',data:{'confirm':'WIPE'});
  Future<ServerResources> adminUserResources(int id)=>api.get('/admin/users/$id/resources').then((j)=>ServerResources.fromJson(_json(j)));
  Future<List<BotModel>> adminUserBots(int id)=>api.get('/admin/users/$id/bots').then((j)=>_models(j,BotModel.fromJson));
  Future<String> adminBotLogs(int id,String f,{int lines=200})=>api.get('/admin/users/$id/bots/${Uri.encodeComponent(f)}/logs',q:{'lines':lines.clamp(1,2000)}).then(_text);
  Future<List<FileModel>> adminUserFiles(int id,String dir)=>api.get('/admin/users/$id/files',q:{'directory':dir}).then((j)=>_models(j,FileModel.fromJson));
  Future<String> adminUserFileContent(int id,String file)=>api.get('/admin/users/$id/files/content',q:{'file':file}).then(_text);
  Future<List<PoolServerModel>> pool({bool live=false})=>api.get('/admin/pool',q:{'live':live}).then((j)=>_models(j,PoolServerModel.fromJson));
  Future<void> addPool(String key,String serverId,String label)=>api.post('/admin/pool',data:{'api_key':key,'server_id':serverId,'label':label});
  Future<void> deletePool(int id)=>api.delete('/admin/pool/$id');
  Future<void> redeployAll(bool restart)=>api.post('/admin/redeploy-all',data:{'restart':restart});
  Future<Map<String,dynamic>> adminSettings()=>api.get('/admin/settings').then(_json);
  Future<void> updateAdminSettings({bool? maintenance,bool? registrationOpen,bool? requireApproval,String? inviteCode})=>api.post('/admin/settings',data:{'maintenance':maintenance,'registration_open':registrationOpen,'require_approval':requireApproval,'invite_code':inviteCode});
  Future<List<AnnouncementModel>> adminAnnouncements()=>api.get('/admin/announcements').then((j)=>_models(j,AnnouncementModel.fromJson));
  Future<void> createAnnouncement(String text)=>api.post('/admin/announcements',data:{'text':text});
  Future<void> deleteAnnouncement(int id)=>api.delete('/admin/announcements/$id');
  Future<List<AuditLogModel>> audit({int limit=100,int? userId,String action=''})=>api.get('/admin/audit',q:{'limit':limit.clamp(1,1000),'user_id':userId,'action':action}).then((j)=>_models(j,AuditLogModel.fromJson));
  Future<Map<String,dynamic>> metrics({int hours=24})=>api.get('/admin/metrics',q:{'hours':hours}).then(_json);
  Future<String> exportUsers()=>api.get('/admin/export/users.csv').then(_text);
  Future<String> exportAudit({int limit=1000})=>api.get('/admin/export/audit.csv',q:{'limit':limit}).then(_text);
  Future<void> createDbBackup()=>api.post('/admin/db-backup');
  Future<List<Map<String,dynamic>>> dbBackups()=>api.get('/admin/db-backups').then((j)=>_models(j,(m)=>m));
}
