int _int(dynamic value) => value is num ? value.toInt() : int.tryParse('$value') ?? 0;
double _double(dynamic value) => value is num ? value.toDouble() : double.tryParse('$value') ?? 0;
bool _bool(dynamic value, [bool fallback = false]) => value is bool ? value : fallback;
String _string(dynamic value, [String fallback = '']) => value?.toString() ?? fallback;
Map<String, dynamic> _map(dynamic value) => value is Map ? Map<String, dynamic>.from(value) : <String, dynamic>{};
List<dynamic> _list(dynamic value) => value is List ? value : const [];

class SessionModel { const SessionModel({required this.token, required this.role, this.serverReady}); final String token, role; final bool? serverReady; factory SessionModel.fromJson(Map<String,dynamic> j)=>SessionModel(token:_string(j['token']),role:_string(j['role'],'user'),serverReady:j['server_ready'] is bool ? j['server_ready'] as bool : null); }
class UserProfile { const UserProfile({this.id=0,this.username='',this.role='user',this.expiresAt,this.daysLeft,this.maxBots,this.hasServer=false,this.createdAt,this.active=true,this.serverName}); final int id; final String username,role; final String? expiresAt,createdAt,serverName; final int? daysLeft,maxBots; final bool hasServer,active; factory UserProfile.fromJson(Map<String,dynamic> j)=>UserProfile(id:_int(j['id']),username:_string(j['username']),role:_string(j['role'],'user'),expiresAt:j['expires_at']?.toString(),daysLeft:j['days_left']==null?null:_int(j['days_left']),maxBots:j['max_bots']==null?null:_int(j['max_bots']),hasServer:_bool(j['has_server']),createdAt:j['created_at']?.toString(),active:_bool(j['active'],true),serverName:j['server_name']?.toString()??j['server_id']?.toString()); }
class AnnouncementModel { const AnnouncementModel({this.id=0,required this.text,this.createdAt}); final int id; final String text; final String? createdAt; factory AnnouncementModel.fromJson(Map<String,dynamic> j)=>AnnouncementModel(id:_int(j['id']),text:_string(j['text']),createdAt:j['created_at']?.toString()); }
class NotificationModel { const NotificationModel({this.id=0,this.title='',this.message='',this.type='info',this.read=false,this.createdAt}); final int id; final String title,message,type; final bool read; final String? createdAt; factory NotificationModel.fromJson(Map<String,dynamic> j)=>NotificationModel(id:_int(j['id']),title:_string(j['title']??j['type']),message:_string(j['message']??j['text']),type:_string(j['type'],'info'),read:_bool(j['read']),createdAt:j['created_at']?.toString()??j['ts']?.toString()); }
class ServerResources { const ServerResources({this.memoryBytes=0,this.memoryTotal=0,this.cpu=0,this.diskBytes=0,this.diskTotal=0,this.networkRx=0,this.networkTx=0,this.uptime=0}); final int memoryBytes,memoryTotal,diskBytes,diskTotal,networkRx,networkTx,uptime; final double cpu; factory ServerResources.fromJson(Map<String,dynamic> j)=>ServerResources(memoryBytes:_int(j['memory_bytes']??j['ram_used']),memoryTotal:_int(j['memory_total']??j['ram_total']),cpu:_double(j['cpu_absolute']??j['cpu']??j['cpu_percent']),diskBytes:_int(j['disk_bytes']??j['disk_used']),diskTotal:_int(j['disk_total']),networkRx:_int(j['network_rx_bytes']??j['network_rx']),networkTx:_int(j['network_tx_bytes']??j['network_tx']),uptime:_int(j['uptime'])); }
class ServerModel { const ServerModel({this.name='',this.state='',required this.resources,this.limits=const {},this.autoRestart=false}); final String name,state; final ServerResources resources; final Map<String,dynamic> limits; final bool autoRestart; factory ServerModel.fromJson(Map<String,dynamic> j)=>ServerModel(name:_string(j['name']??j['server_name']),state:_string(j['state']??j['status']),resources:ServerResources.fromJson(_map(j['resources']??j)),limits:_map(j['limits']),autoRestart:_bool(j['auto_restart'])); bool get running=>state.toLowerCase()=='running'||state.toLowerCase()=='online'; }
class ProcessModel { const ProcessModel({this.pid=0,this.name='',this.cpu=0,this.ram=0,this.status=''}); final int pid; final String name,status; final double cpu; final int ram; factory ProcessModel.fromJson(Map<String,dynamic> j)=>ProcessModel(pid:_int(j['pid']),name:_string(j['name']),cpu:_double(j['cpu']),ram:_int(j['ram']??j['memory']),status:_string(j['status'])); }
class StartupVariable { const StartupVariable({required this.key,required this.value,required this.editable,this.description='' }); final String key,value; final bool editable; final String description; factory StartupVariable.fromJson(Map<String,dynamic> j)=>StartupVariable(key:_string(j['key']),value:_string(j['value']),editable:_bool(j['editable'],true),description:_string(j['description'])); }
class FileModel { const FileModel({required this.name,required this.isFile,this.size=0,this.modified,this.path,this.type}); final String name; final bool isFile; final int size; final String? modified,path,type; factory FileModel.fromJson(Map<String,dynamic> j)=>FileModel(name:_string(j['name']??j['filename']),isFile:j['is_file'] is bool?_bool(j['is_file']):_string(j['type'])!='directory',size:_int(j['size']),modified:j['modified_at']?.toString()??j['modified']?.toString(),path:j['path']?.toString(),type:j['type']?.toString()); }
class FileMeta { const FileMeta({this.path='',this.name='',this.size=0,this.type='',this.modified,this.permissions}); final String path,name,type; final int size; final String? modified,permissions; factory FileMeta.fromJson(Map<String,dynamic> j)=>FileMeta(path:_string(j['path']),name:_string(j['name']),size:_int(j['size']),type:_string(j['type']),modified:j['modified']?.toString(),permissions:j['permissions']?.toString()); }
class SearchFileModel extends FileModel { const SearchFileModel({required super.name,required super.isFile,super.size,super.modified,super.path,super.type}); factory SearchFileModel.fromJson(Map<String,dynamic> j)=>SearchFileModel(name:_string(j['name']),isFile:_bool(j['is_file'],true),size:_int(j['size']),modified:j['modified']?.toString(),path:j['path']?.toString(),type:j['type']?.toString()); }
class UploadModel { const UploadModel({this.id='',this.filename='',this.size=0,this.uploaded=0,this.status=''}); final String id,filename,status; final int size,uploaded; factory UploadModel.fromJson(Map<String,dynamic> j)=>UploadModel(id:_string(j['upid']??j['id']),filename:_string(j['filename']),size:_int(j['size']),uploaded:_int(j['uploaded']),status:_string(j['status'])); }
class BackupModel { const BackupModel({required this.uuid,required this.name,this.bytes=0,this.createdAt,this.locked=false,this.status}); final String uuid,name; final int bytes; final String? createdAt,status; final bool locked; factory BackupModel.fromJson(Map<String,dynamic> j)=>BackupModel(uuid:_string(j['uuid']??j['id']),name:_string(j['name'],'backup'),bytes:_int(j['bytes']??j['size']),createdAt:j['created_at']?.toString(),locked:_bool(j['locked']),status:j['status']?.toString()); }
class BackupPolicy { const BackupPolicy({this.enabled=false,this.intervalHours=24,this.keep=5}); final bool enabled; final int intervalHours,keep; factory BackupPolicy.fromJson(Map<String,dynamic> j)=>BackupPolicy(enabled:_bool(j['enabled']),intervalHours:_int(j['interval_hours']??24),keep:_int(j['keep']??5)); }
class BotModel { const BotModel({required this.file,required this.enabled,this.state='Stopped',this.envKeys=const [],this.restarts=0,this.crashes=0,this.startedAt,this.lastExitCode,this.lastActivity}); final String file,state; final bool enabled; final List<String> envKeys; final int restarts,crashes; final String? startedAt,lastActivity; final int? lastExitCode; factory BotModel.fromJson(Map<String,dynamic> j)=>BotModel(file:_string(j['file']??j['name']),enabled:_bool(j['enabled'],true),state:_string(j['state']??j['status'],_bool(j['enabled'],true)?'Running':'Stopped'),envKeys:_list(j['env_keys']).map(_string).toList(),restarts:_int(j['restarts']??j['restart_count']),crashes:_int(j['crashes']??j['crash_count']),startedAt:j['started_at']?.toString(),lastExitCode:j['last_exit_code']==null?null:_int(j['last_exit_code']),lastActivity:j['last_activity']?.toString()); }
class CrashModel { const CrashModel({this.date='',this.reason='',this.exitCode,this.restartCount=0,this.status=''}); final String date,reason,status; final int? exitCode; final int restartCount; factory CrashModel.fromJson(Map<String,dynamic> j)=>CrashModel(date:_string(j['date']??j['created_at']),reason:_string(j['reason']),exitCode:j['exit_code']==null?null:_int(j['exit_code']),restartCount:_int(j['restart_count']),status:_string(j['status'])); }
class BotPolicy { const BotPolicy({this.mode='',this.delay=0,this.maxFastCrashes=0}); final String mode; final int delay,maxFastCrashes; factory BotPolicy.fromJson(Map<String,dynamic> j)=>BotPolicy(mode:_string(j['mode']),delay:_int(j['delay']),maxFastCrashes:_int(j['max_fast_crashes'])); }
class AdminStats { const AdminStats({this.users=0,this.active=0,this.pending=0,this.banned=0,this.new7Days=0,this.poolTotal=0,this.poolUsed=0,this.poolFree=0,this.logins24h=0,this.maintenance=false,this.registration=true}); final int users,active,pending,banned,new7Days,poolTotal,poolUsed,poolFree,logins24h; final bool maintenance,registration; factory AdminStats.fromJson(Map<String,dynamic> j)=>AdminStats(users:_int(j['users']),active:_int(j['active_users']??j['active']),pending:_int(j['pending']??j['pending_requests']),banned:_int(j['banned']),new7Days:_int(j['new_7_days']??j['new7days']),poolTotal:_int(j['pool_total']),poolUsed:_int(j['pool_used']),poolFree:_int(j['pool_free']),logins24h:_int(j['logins_24h']),maintenance:_bool(j['maintenance']),registration:_bool(j['registration'],true)); }
class AdminUserModel { const AdminUserModel({required this.id,required this.username,required this.role,required this.active,this.serverId,this.banned=false,this.expiry,this.maxBots,this.note}); final int id; final String username,role; final bool active,banned; final String? serverId,expiry,note; final int? maxBots; factory AdminUserModel.fromJson(Map<String,dynamic> j)=>AdminUserModel(id:_int(j['id']),username:_string(j['username']),role:_string(j['role'],'user'),active:_bool(j['active'],true),serverId:j['server_id']?.toString()??j['server']?.toString(),banned:_bool(j['banned']),expiry:j['expiry']?.toString()??j['expires_at']?.toString(),maxBots:j['max_bots']==null?null:_int(j['max_bots']),note:j['note']?.toString()); }
class PoolServerModel { const PoolServerModel({required this.id,required this.label,required this.serverId,this.username,this.state}); final int id; final String label,serverId; final String? username,state; factory PoolServerModel.fromJson(Map<String,dynamic> j)=>PoolServerModel(id:_int(j['id']),label:_string(j['label']),serverId:_string(j['server_id']),username:j['username']?.toString()??j['assigned_user']?.toString(),state:j['state']?.toString()); }
class AuditLogModel { const AuditLogModel({required this.id,required this.ts,required this.action,this.userId,this.detail,this.username}); final int id; final String ts,action; final int? userId; final String? detail,username; factory AuditLogModel.fromJson(Map<String,dynamic> j)=>AuditLogModel(id:_int(j['id']),ts:_string(j['ts']??j['created_at']),action:_string(j['action']),userId:j['user_id']==null?null:_int(j['user_id']),detail:j['detail']?.toString(),username:j['username']?.toString()); }
class AdminRequest { const AdminRequest({this.id=0,this.username='',this.status='',this.createdAt}); final int id; final String username,status; final String? createdAt; factory AdminRequest.fromJson(Map<String,dynamic> j)=>AdminRequest(id:_int(j['id']??j['uid']),username:_string(j['username']),status:_string(j['status'],'pending'),createdAt:j['created_at']?.toString()); }

String bytesText(num bytes){if(bytes<1024)return '${bytes.toInt()} B';if(bytes<1048576)return '${(bytes/1024).toStringAsFixed(1)} KB';if(bytes<1073741824)return '${(bytes/1048576).toStringAsFixed(1)} MB';return '${(bytes/1073741824).toStringAsFixed(1)} GB';}
String uptimeText(int seconds){final d=seconds~/86400,h=(seconds%86400)~/3600,m=(seconds%3600)~/60;if(d>0)return '${d}d ${h}h';if(h>0)return '${h}h ${m}m';return '${m}m';}
